Update aseprite_build_deploy.yml

diff --git a/.github/workflows/aseprite_build_deploy.yml b/.github/workflows/aseprite_build_deploy.yml
--- a/.github/workflows/aseprite_build_deploy.yml
+++ b/.github/workflows/aseprite_build_deploy.yml
@@ -156,12 +156,22 @@ jobs:
      #   working-directory: aseprite/build
      #   shell: cmd
      #   run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_IGNORE_PATH='C:/ProgramData/chocolatey/bin/;C:/Strawberry/c/bin/' -DLAF_BACKEND=skia -DSKIA_DIR=../../skia -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64 -G Ninja ..
+      - name: Verify Submodules
+        shell: cmd
+        run: |
+          if exist aseprite\third_party\libjpeg-turbo\CMakeLists.txt (
+             echo "Submodules are present!"
+           ) else (
+             echo "Submodules are MISSING!"
+             exit 1
+             )
       - name: (Windows) Run CMake
         if: matrix.os == 'windows-latest'
-        working-directory: aseprite/build
         # We remove the 'working-directory' line here and handle it in the 'run' block for safety
         shell: cmd
         run: |
+          if exist aseprite\build rd /s /q aseprite\build
+          mkdir aseprite\build
           if not exist aseprite\build mkdir aseprite\build
           cd aseprite\build
           cmake -G Ninja .. ^
@@ -169,10 +179,22 @@ jobs:
            -DLAF_BACKEND=skia ^
            -DSKIA_DIR=%GITHUB_WORKSPACE%\skia ^
            -DSKIA_LIBRARY_DIR=%GITHUB_WORKSPACE%\skia ^
-           -DSKIA_LIBRARY=%GITHUB_WORKSPACE%\skia\skia.lib
+           -DSKIA_LIBRARY=%GITHUB_WORKSPACE%\skia\skia.lib ^
+           -DSKIA_LIBRARY=%GITHUB_WORKSPACE%\skia\skia.lib ^
+           -DCMAKE_IGNORE_PATH="C:/ProgramData/chocolatey/bin/;C:/Strawberry/c/bin/" ^
+           -DUSE_SHARED_ZLIB=OFF ^
+           -DUSE_SHARED_LIBPNG=OFF ^
+           -DUSE_SHARED_TINYXML=OFF ^
+           -DUSE_SHARED_PIXMAN=OFF ^
+           -DUSE_SHARED_FREETYPE=OFF ^
+           -DUSE_SHARED_HARFBUZZ=OFF ^
+           -DUSE_SHARED_LIBJPEG=OFF ^
+           -DUSE_SHARED_GIF=OFF
         #  -DSKIA_LIBRARY=%GITHUB_WORKSPACE%\skia\out\Debug-x64\skia.lib
         #  -DSKIA_LIBRARY_DIR=%GITHUB_WORKSPACE%\skia\out\Release-x64 ^
         #  -DCMAKE_IGNORE_PATH="C:/ProgramData/chocolatey/bin/;C:/Strawberry/c/bin/"
+
+        
       - name: (Ubuntu) Run CMake
         if: matrix.os == 'ubuntu-latest'
         working-directory: aseprite/build
